FROM node:20-alpine
WORKDIR /bot
COPY telegram/package.json ./
RUN npm i -g pnpm && pnpm install --prod
COPY telegram ./telegram
COPY lib ./lib
COPY prisma ./prisma
RUN pnpm dlx prisma generate
CMD ["node","telegram/index.js"]
