version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: nextchat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: [ "nextchat-db:/var/lib/postgresql/data" ]

  nextchat:
    image: ghcr.io/${IMAGE_OWNER}/nextchat:latest
    env_file: .env.prod
    depends_on: [ db ]
    restart: unless-stopped
    ports: [ "3000:3000" ]

  telegram-bot:
    image: ghcr.io/${IMAGE_OWNER}/nextchat-telegram:latest
    env_file: .env.prod
    depends_on: [ db ]
    restart: unless-stopped
    ports: [ "3001:3001" ]

volumes:
  nextchat-db:
